### PR TITLE
Redirects from FA blog to dbt blog (not to merge until posts are live on dbt ghost)

### PR DESCRIPTION
**Pull request by krevitt**
Following decision-making w/ Tristan in this Sheet: https://docs.google.com/spreadsheets/d/1xinUAs5swIpy4MWrKspbeFfkTlJPrQ6zZ4bC-XhY6ik/edit#gid=1816325876

### CODE REVIEW

**Comment by krevitt** [comment]
@lfracalossiFA think we can handle all FA blog redirects here (not in DNS, since there are random paths from Medium that we want to redirect to pages that aren't an exact path match).

Added a redirect from "/" to "https://blog.getdbt.com" to handle the root redirect (instead of DNS), lmk if that makes sense.

[Asana ticket here](https://app.asana.com/0/1199544066268568/1200513994514716) for reference.

**Comment by lfracalossiFA** [comment]
Hey @krevitt, I don't know much about how Ghost works, so I may not be the best one to review this. I actually didn't know we had a version control or CI/CD workflow for any of the blogs! I might ask Drew to review, or for more info -- afaict he knows this workflow the best. 

Are we not handling the blog.fishtown -> blog.getdbt with a DNS flip, then?

**Comment by krevitt** [comment]
> Hey @krevitt, I don't know much about how Ghost works, so I may not be the best one to review this. I actually didn't know we had a version control or CI/CD workflow for any of the blogs! I might ask Drew to review, or for more info -- afaict he knows this workflow the best.
> 
> Are we not handling the blog.fishtown -> blog.getdbt with a DNS flip, then?

Thanks Lise - adding @drewbanin as reviewer here!

And yes that's right, think we can do all blog -> blog redirects here instead of with DNS.

**Review by drewbanin — APPROVED** [review]
This LGTM @krevitt! I unfortunately don't know that we can test this in the staging env -- IIRC Netlify doesn't handle redirects for preview deploys. That sounds funny, but I just tested some of these changes out and didn't have any luck :/

Changes look good though - lmk if you want to dig deeper together into testing this out in the staging env

**Comment by drewbanin** [comment]
@krevitt - @lfracalossiFA actually set me straight here.... I was totally wrong and these redirects are not actually deployed through Netlify! I think that this json file actually need to be _uploaded to Ghost_, which is where the redirects will be handled

So, that's why we're not seeing the redirects working in the staging env. My instinct is that we should:
1. Make sure we know how to update the redirects.json file in Ghost for blog.fishtownanalytics.com
2. Commit this change when we feel good about it
3. Plan on uploading this json file to Ghost on launch day
4. Update the readme :)

S/o to Lise for the great intuition and pointer on the fact that redirects _definitely do_ work in the Netlify staging env!

**Comment by krevitt** [comment]
Ahhh so we version control here just for history tracking, but it’s a manual update process

**Pull request merged**
